### ISSUE TITLE
Gérer les clés étrangères entre les différentes tables

### ISSUE THREAD

**Issue by AlexandreTO** [AlexandreTO/Projet#23]
## Base de données et relations sous Symfony

Pour pouvoir gérer les clés étrangères sous Symfony,  il faut modifier l'**annotation** de la variable dans l'entité avec des relations *ManyToOne*,  *OneToMany*, *ManyToMany* .
C.f  [Symfony Relations]( https://symfony.com/doc/current/doctrine/associations.html )

Information supplémentaires pour les relations : 
- Une Catégorie peut contenir plusieurs Produits
- Un (des) Produit (s) peut(vent) faire parti (s) d'une seule Catégorie
- Un code promo peut faire référence à plusieurs produits. (A vérifier)

Pour vérifier que si les relations fonctionnent bien,  Il faut coder les fixtures avec Faker pour chaque table après avoir faire les relations et de générer ces fixtures afin de pouvoir vérifier les relations dans la base de données (locale pour l'instant)

### Mise à jour

Renommer les champs des entités en anglais pour être conforme.

**Cette issue est juste là pour faire un point sur le prochain travail, créer votre issue en indiquant ce que vous allez faire**

### TODO

- [x] Relation entre les tables
- [x] Rédaction des fixtures
- [x] Renommage des champs dans les tables
