### ISSUE TITLE
Faire une page connexion

### ISSUE THREAD

**Issue by AlexandreTO** [AlexandreTO/Projet#40]
Créer une page connexion permettant aux utilisateurs de pouvoir créer un compte via un formulaire. 
Les comptes auront chacun un rôle spécifique et chaque rôle a accès à certaines pages.

## TODO

- [x] Formulaire pour créer les comptes
- [x] Enregistrer les comptes dans la base de données avec un mot de passe sécurisé cf #26 
- [x] Pouvoir se connecter via la page de connexion
- [x] Refaire le css pour le formulaire d'inscription
