### ISSUE TITLE
Implémentation d'un ajout / suppression de produit

### ISSUE THREAD

**Issue by AlexandreTO** [AlexandreTO/Projet#41]
Il faut pouvoir ajouter et supprimer des produits dans la base de données via un formulaire. 
Se réferer à la base de données et/ou à l'entité pour savoir quel champs mettre dans le formulaire

## TODO

- [x] Faire un formulaire pour le produit
- [x] Gérer l'ajout dans la base de données en back
- [x] Ajouter un bouton afin de supprimer un produit
